services:
  hioshop-admin:
    image: beisitech/hioshop-admin:latest
    # image: hioshop-admin # 本地镜像测试
    volumes:
      - "/caddy/data:/data"
    container_name: hioshop-admin
    restart: on-failure:3
    env_file:
      - .env
    networks:
      - beisi-network

networks:
  beisi-network:
    external: true
    name: beisi-shared-network
